"""Google Colab / Kaggle runbook for fine-tuning cyrillic_g2 on T4 GPU.

Paste this file as a single Colab cell. It assumes you have uploaded
the bootstrapped dataset (``datasets/finetune_ru/``) to your Google
Drive. The notebook will:

    1. Mount Google Drive (source of the dataset + destination for the
       trained .pth).
    2. Install PyTorch + numpy + opencv + ninja + fire + natsort +
       lmdb + pillow matching the EasyOCR trainer requirements.
    3. Clone the EasyOCR repo (sparse, trainer/ subfolder only).
    4. Download the stock ``cyrillic_g2.pth`` (~15 MB) to seed from.
    5. Write the trainer YAML config pointing at
       ``/content/drive/MyDrive/finetune_ru``.
    6. Launch training for ``EPOCHS`` × 1000 iterations. On a T4 GPU
       one epoch takes ~40-60s, so 100 epochs ≈ 1-1.5h. The best
       checkpoint is copied back to Drive when training finishes.
    7. Drop the fine-tuned .pth into ``OCR-tool/resources/
       easyocr_models/cyrillic_g2.pth`` on your next ``git pull`` +
       ``python build.py`` — no additional wiring required.

Free-tier caveats:
    * Colab free T4: 12h/session hard cap. ``EPOCHS=100`` (~1.5h) is
      safe with headroom. ``EPOCHS=300`` (~4h) is the sweet spot for
      the full 2k-crop dataset, still within free-tier.
    * Kaggle free: P100 or T4, 30h/week. Identical workflow — swap
      the Drive mount for Kaggle's ``/kaggle/input/`` + ``/kaggle/
      working/``.

Prerequisites on your local machine:
    1. ``python scripts/finetune/bootstrap_dataset.py`` — builds
       ``datasets/finetune_ru/{training,validation}/{*.jpg,labels.csv}``
    2. Upload ``datasets/finetune_ru/`` to Google Drive as
       ``My Drive/finetune_ru/``.
    3. Run ``python scripts/finetune/colab_finetune.py > cell.py``
       to render the substituted cell, then paste ``cell.py`` into a
       new Colab notebook and hit Run.
    4. After training, download
       ``My Drive/finetune_ru/out/best_accuracy.pth`` and place it at
       ``resources/easyocr_models/cyrillic_g2.pth`` in the local repo,
       then ``python build.py`` bundles the fine-tuned recognizer.

Rollback (restore stock weights):
    ``cp resources/easyocr_models/cyrillic_g2.pth.stock \\
        resources/easyocr_models/cyrillic_g2.pth``
"""

from __future__ import annotations

# === Edit these 3 variables before running ==================================
DRIVE_DATASET_DIR = "/content/drive/MyDrive/finetune_ru"
EPOCHS = 100        # 100 ≈ 1.5h on T4; 300 = sweet spot for 2k crops
BATCH_SIZE = 32     # T4 has 16GB — 32 fits easily for imgH=64

# === Don't edit below =======================================================

# Placeholders are __NAME__ style — avoids any conflict with curly braces
# inside the Python / YAML content of the generated Colab cell.
_COLAB_TEMPLATE = r"""
# ── Cell generated by scripts/finetune/colab_finetune.py ──────────────────

# 1. Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Install deps
import subprocess, sys
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q',
    'torch==2.0.1', 'torchvision==0.15.2',
    'natsort', 'lmdb', 'nltk', 'fire',
    'opencv-python-headless', 'Pillow', 'numpy==1.24.4'])

# 3. Clone trainer (sparse checkout — only trainer/ subfolder)
import subprocess
subprocess.check_call(['bash', '-c',
    'rm -rf /content/EasyOCR && '
    'git clone --depth 1 --filter=blob:none --sparse '
    'https://github.com/JaidedAI/EasyOCR.git /content/EasyOCR && '
    'cd /content/EasyOCR && '
    'git sparse-checkout set trainer'])

# 4. Fetch stock cyrillic_g2 weights
import urllib.request, pathlib
base_weights = pathlib.Path('/content/base_weights/cyrillic_g2.pth')
base_weights.parent.mkdir(parents=True, exist_ok=True)
if not base_weights.exists():
    urls = [
        'https://www.jaided.ai/read_download_model/cyrillic_g2.pth',
        'https://github.com/JaidedAI/EasyOCR/releases/download/v1.6.2/cyrillic_g2.pth',
    ]
    for url in urls:
        try:
            print(f'Downloading weights from {url} …')
            urllib.request.urlretrieve(url, base_weights)
            break
        except Exception as e:
            print(f'  failed: {e}')
    else:
        raise RuntimeError('Could not download cyrillic_g2.pth — check network.')
print('Base weights:', base_weights)

# 5. Write trainer YAML config
import pathlib
DATA = r"__DRIVE_DATASET_DIR__"
EPOCHS = __EPOCHS__
BATCH = __BATCH_SIZE__
num_iter = EPOCHS * 1000

import string as _string
_sym = " " + _string.punctuation + " €₽"
_sym_yaml = _sym.replace("'", "''")
cfg = "\n".join([
    "number: '0123456789'",
    f"symbol: '{_sym_yaml}'",
    "lang_char: 'абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'",
    "experiment_name: 'ru_finetune'",
    f"train_data: '{DATA}'",
    f"valid_data: '{DATA}/validation'",
    "manualSeed: 1111",
    "workers: 2",
    f"batch_size: {BATCH}",
    f"num_iter: {num_iter}",
    "valInterval: 500",
    f"saved_model: '{str(base_weights)}'",
    "FT: True",
    "optim: 'adam'",
    "lr: 0.0005",
    "beta1: 0.9",
    "rho: 0.95",
    "eps: 0.00000001",
    "grad_clip: 5",
    "select_data: 'training'",
    "batch_ratio: '1.0'",
    "total_data_usage_ratio: '1.0'",
    "batch_max_length: 34",
    "imgH: 64",
    "imgW: 600",
    "rgb: False",
    "contrast_adjust: 0.0",
    "data_filtering_off: False",
    "PAD: True",
    "Transformation: 'None'",
    "FeatureExtraction: 'ResNet'",
    "SequenceModeling: 'BiLSTM'",
    "Prediction: 'CTC'",
    "num_fiducial: 20",
    "input_channel: 1",
    "output_channel: 256",
    "hidden_size: 256",
    "decode: 'greedy'",
    "new_prediction: False",
    "freeze_FeatureFxtraction: False",
    "freeze_SequenceModeling: False",
    "device: 'cuda'",
]) + "\n"

cfg_path = pathlib.Path('/content/EasyOCR/trainer/saved_models/ru_finetune.yaml')
cfg_path.parent.mkdir(parents=True, exist_ok=True)
cfg_path.write_text(cfg, encoding='utf-8')
print('Config written:', cfg_path)

# 6. Train
import subprocess, os
result = subprocess.run(
    ['python', 'train.py', '--config_name', 'ru_finetune'],
    cwd='/content/EasyOCR/trainer',
)
print(f'Training finished with exit code {result.returncode}')

# 7. Copy best checkpoint back to Drive
import shutil, pathlib
best = pathlib.Path('/content/EasyOCR/trainer/saved_models/ru_finetune/best_accuracy.pth')
out_dir = pathlib.Path(DATA) / 'out'
out_dir.mkdir(parents=True, exist_ok=True)
if best.exists():
    dest = out_dir / 'best_accuracy.pth'
    shutil.copy2(best, dest)
    print('Fine-tuned weights saved to Drive:', dest)
    print('Next: copy to resources/easyocr_models/cyrillic_g2.pth, then python build.py')
else:
    print('WARNING: no best_accuracy.pth found — check training log above.')
"""


def render(
    drive_dataset_dir: str = DRIVE_DATASET_DIR,
    epochs: int = EPOCHS,
    batch_size: int = BATCH_SIZE,
) -> str:
    return (
        _COLAB_TEMPLATE
        .replace("__DRIVE_DATASET_DIR__", drive_dataset_dir)
        .replace("__EPOCHS__", str(epochs))
        .replace("__BATCH_SIZE__", str(batch_size))
    )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--drive-dir", default=DRIVE_DATASET_DIR,
        help="Google Drive path to finetune_ru/ (default: %(default)s)",
    )
    parser.add_argument("--epochs", type=int, default=EPOCHS)
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    args = parser.parse_args()

    print(render(args.drive_dir, args.epochs, args.batch_size))
