"""Google Colab / Kaggle runbook for fine-tuning cyrillic_g2 on T4 GPU.

Paste this file as a single Colab cell. It assumes you have uploaded
the bootstrapped dataset (``datasets/finetune_ru/``) to your Google
Drive. The notebook will:

    1. Mount Google Drive (source of the dataset + destination for the
       trained .pth).
    2. Install PyTorch + numpy + opencv + ninja + fire + natsort +
       lmdb + pillow matching the EasyOCR trainer requirements.
    3. Clone the EasyOCR repo (sparse, trainer/ subfolder only).
    4. Download the stock ``cyrillic_g2.pth`` (~15 MB) to seed from.
    5. Write the trainer YAML config pointing at
       ``/content/drive/MyDrive/finetune_ru``.
    6. Launch training for ``EPOCHS`` × 1000 iterations. On a T4 GPU
       one epoch takes ~40-60s, so 100 epochs ≈ 1-1.5h. The best
       checkpoint is copied back to Drive when training finishes.
    7. Drop the fine-tuned .pth into ``OCR-tool/resources/
       easyocr_models/cyrillic_g2.pth`` on your next ``git pull`` +
       ``python build.py`` — no additional wiring required.

Free-tier caveats:
    * Colab free T4: 12h/session hard cap. ``EPOCHS=100`` (~1.5h) is
      safe with headroom. ``EPOCHS=300`` (~4h) is the sweet spot for
      the full 2k-crop dataset, still within free-tier.
    * Kaggle free: P100 or T4, 30h/week. Identical workflow — swap
      the Drive mount for Kaggle's ``/kaggle/input/`` + ``/kaggle/
      working/``.

Prerequisites on your local machine:
    1. ``python scripts/finetune/bootstrap_dataset.py`` — builds
       ``datasets/finetune_ru/{training,validation}/{*.jpg,labels.csv}``
    2. Upload ``datasets/finetune_ru/`` to Google Drive as
       ``My Drive/finetune_ru/``.
    3. Run ``python scripts/finetune/colab_finetune.py > cell.py``
       to render the substituted cell, then paste ``cell.py`` into a
       new Colab notebook and hit Run.
    4. After training, download
       ``My Drive/finetune_ru/out/best_accuracy.pth`` and place it at
       ``resources/easyocr_models/cyrillic_g2.pth`` in the local repo,
       then ``python build.py`` bundles the fine-tuned recognizer.

Rollback (restore stock weights):
    ``cp resources/easyocr_models/cyrillic_g2.pth.stock \\
        resources/easyocr_models/cyrillic_g2.pth``
"""

from __future__ import annotations

# === Edit these 3 variables before running ==================================
DRIVE_DATASET_DIR = "/content/drive/MyDrive/finetune_ru"
EPOCHS = 100        # 100 ≈ 1.5h on T4; 300 = sweet spot for 2k crops
BATCH_SIZE = 32     # T4 has 16GB — 32 fits easily for imgH=64

# === Don't edit below =======================================================

# Placeholders are __NAME__ style — avoids any conflict with curly braces
# inside the Python / YAML content of the generated Colab cell.
_COLAB_TEMPLATE = r"""
# ── Cell generated by scripts/finetune/colab_finetune.py ──────────────────

# 1. Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Install deps (use Colab's pre-installed torch/torchvision/numpy — only add
#    the trainer's extras. Pinning torch==2.0.1 fails on modern Colab Python.)
import subprocess, sys
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q',
    'natsort', 'lmdb', 'nltk', 'fire', 'pandas',
    'opencv-python-headless', 'Pillow', 'PyYAML'])

# 3. Clone trainer (sparse checkout — only trainer/ subfolder)
import subprocess
subprocess.check_call(['bash', '-c',
    'rm -rf /content/EasyOCR && '
    'git clone --depth 1 --filter=blob:none --sparse '
    'https://github.com/JaidedAI/EasyOCR.git /content/EasyOCR && '
    'cd /content/EasyOCR && '
    'git sparse-checkout set trainer'])

# 4. Fetch stock cyrillic_g2 weights (shipped as a ZIP in EasyOCR releases)
import urllib.request, pathlib, zipfile, io
base_weights = pathlib.Path('/content/base_weights/cyrillic_g2.pth')
base_weights.parent.mkdir(parents=True, exist_ok=True)
if not base_weights.exists():
    urls = [
        'https://github.com/JaidedAI/EasyOCR/releases/download/v1.6.1/cyrillic_g2.zip',
        'https://github.com/JaidedAI/EasyOCR/releases/download/pre-v1.1.6/cyrillic_g2.zip',
    ]
    for url in urls:
        try:
            print(f'Downloading weights from {url} …')
            req = urllib.request.Request(url, headers={'User-Agent': 'easyocr-colab'})
            with urllib.request.urlopen(req) as r:
                blob = r.read()
            with zipfile.ZipFile(io.BytesIO(blob)) as zf:
                # ZIP contains a single .pth at its root.
                members = [n for n in zf.namelist() if n.endswith('.pth')]
                if not members:
                    raise RuntimeError(f'No .pth inside {url}')
                with zf.open(members[0]) as src, open(base_weights, 'wb') as dst:
                    dst.write(src.read())
            break
        except Exception as e:
            print(f'  failed: {e}')
    else:
        raise RuntimeError('Could not download cyrillic_g2.pth — check network.')
print('Base weights:', base_weights, f'({base_weights.stat().st_size / 1e6:.1f} MB)')

# 4b. Patch trainer for PyTorch 2.x / Python 3 compatibility
# - torch._utils._accumulate removed in PyTorch 2.x → itertools.accumulate
# - iterator.next() → next(iterator) (Python 3)
import pathlib
_ds = pathlib.Path('/content/EasyOCR/trainer/dataset.py')
_src = _ds.read_text(encoding='utf-8')
if 'from itertools import accumulate as _accumulate' not in _src:
    _src = _src.replace(
        'from torch._utils import _accumulate',
        'try:\n    from torch._utils import _accumulate\n'
        'except ImportError:\n    from itertools import accumulate as _accumulate'
    )
    _src = _src.replace('data_loader_iter.next()', 'next(data_loader_iter)')
    _src = _src.replace(
        'self.dataloader_iter_list[i].next()',
        'next(self.dataloader_iter_list[i])'
    )
    _ds.write_text(_src, encoding='utf-8')
    print('Patched trainer/dataset.py (PyTorch 2.x / Python 3 compat)')

# 4c. Patch train.py for PyTorch ≥ 2.6 (weights_only=True default rejects
#     arbitrary pickled state_dicts).
_tr = pathlib.Path('/content/EasyOCR/trainer/train.py')
_tsrc = _tr.read_text(encoding='utf-8')
if 'weights_only=False' not in _tsrc:
    _tsrc = _tsrc.replace(
        'pretrained_dict = torch.load(opt.saved_model)',
        'pretrained_dict = torch.load(opt.saved_model, weights_only=False)'
    )
    _tr.write_text(_tsrc, encoding='utf-8')
    print('Patched trainer/train.py (torch.load weights_only=False)')

# 5. Write trainer YAML config
import pathlib
DATA = r"__DRIVE_DATASET_DIR__"
EPOCHS = __EPOCHS__
BATCH = __BATCH_SIZE__
num_iter = EPOCHS * 1000

import string as _string
_sym = " " + _string.punctuation + " €₽"
_sym_yaml = _sym.replace("'", "''")
cfg = "\n".join([
    "number: '0123456789'",
    f"symbol: '{_sym_yaml}'",
    "lang_char: 'абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'",
    "experiment_name: 'ru_finetune'",
    f"train_data: '{DATA}'",
    f"valid_data: '{DATA}/validation'",
    "manualSeed: 1111",
    "workers: 2",
    f"batch_size: {BATCH}",
    f"num_iter: {num_iter}",
    "valInterval: 500",
    f"saved_model: '{str(base_weights)}'",
    "FT: True",
    "optim: 'adam'",
    "lr: 0.0005",
    "beta1: 0.9",
    "rho: 0.95",
    "eps: 0.00000001",
    "grad_clip: 5",
    "select_data: 'training'",
    "batch_ratio: '1.0'",
    "total_data_usage_ratio: '1.0'",
    "batch_max_length: 34",
    "imgH: 64",
    "imgW: 600",
    "rgb: False",
    "sensitive: True",
    "contrast_adjust: 0.0",
    "data_filtering_off: False",
    "PAD: True",
    "Transformation: 'None'",
    "FeatureExtraction: 'ResNet'",
    "SequenceModeling: 'BiLSTM'",
    "Prediction: 'CTC'",
    "num_fiducial: 20",
    "input_channel: 1",
    "output_channel: 256",
    "hidden_size: 256",
    "decode: 'greedy'",
    "new_prediction: True",
    "freeze_FeatureFxtraction: False",
    "freeze_SequenceModeling: False",
    "device: 'cuda'",
]) + "\n"

cfg_path = pathlib.Path('/content/EasyOCR/trainer/saved_models/ru_finetune.yaml')
cfg_path.parent.mkdir(parents=True, exist_ok=True)
cfg_path.write_text(cfg, encoding='utf-8')
print('Config written:', cfg_path)

# 6. Train (EasyOCR trainer has no argparse __main__ — drive via notebook-style runner)
import subprocess, pathlib
_runner_lines = [
    'import os, sys, yaml',
    'import torch.backends.cudnn as cudnn',
    'sys.path.insert(0, os.getcwd())',
    'from train import train',
    'from utils import AttrDict',
    "with open(sys.argv[1], encoding='utf-8') as f:",
    '    opt = AttrDict(yaml.safe_load(f))',
    'opt.character = opt.number + opt.symbol + opt.lang_char',
    "os.makedirs(f'./saved_models/{opt.experiment_name}', exist_ok=True)",
    'cudnn.benchmark = True',
    'cudnn.deterministic = False',
    'train(opt, amp=False)',
]
_runner = pathlib.Path('/content/EasyOCR/trainer/_runner.py')
_runner.write_text('\n'.join(_runner_lines) + '\n', encoding='utf-8')

# Stream stdout + stderr line-by-line into the Colab cell so a failing
# train() call is actually visible (subprocess.run without capture swallows
# output in notebook kernels). We also force -u (unbuffered) so progress
# prints appear live, not after process exits.
proc = subprocess.Popen(
    ['python', '-u', str(_runner), str(cfg_path)],
    cwd='/content/EasyOCR/trainer',
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    text=True, bufsize=1,
)
for line in proc.stdout:
    print(line, end='')
rc = proc.wait()
print(f'Training finished with exit code {rc}')

# 7. Copy best checkpoint back to Drive
import shutil, pathlib
best = pathlib.Path('/content/EasyOCR/trainer/saved_models/ru_finetune/best_accuracy.pth')
out_dir = pathlib.Path(DATA) / 'out'
out_dir.mkdir(parents=True, exist_ok=True)
if best.exists():
    dest = out_dir / 'best_accuracy.pth'
    shutil.copy2(best, dest)
    print('Fine-tuned weights saved to Drive:', dest)
    print('Next: copy to resources/easyocr_models/cyrillic_g2.pth, then python build.py')
else:
    print('WARNING: no best_accuracy.pth found — check training log above.')
"""


def render(
    drive_dataset_dir: str = DRIVE_DATASET_DIR,
    epochs: int = EPOCHS,
    batch_size: int = BATCH_SIZE,
) -> str:
    return (
        _COLAB_TEMPLATE
        .replace("__DRIVE_DATASET_DIR__", drive_dataset_dir)
        .replace("__EPOCHS__", str(epochs))
        .replace("__BATCH_SIZE__", str(batch_size))
    )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--drive-dir", default=DRIVE_DATASET_DIR,
        help="Google Drive path to finetune_ru/ (default: %(default)s)",
    )
    parser.add_argument("--epochs", type=int, default=EPOCHS)
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    args = parser.parse_args()

    print(render(args.drive_dir, args.epochs, args.batch_size))
