
# ── Cell generated by scripts/finetune/colab_finetune.py ──────────────────

# 1. Mount Drive (for saving the trained .pth back out of the ephemeral VM).
#    force_remount=False is fine — it no-ops if already mounted.
from google.colab import drive
drive.mount('/content/drive')

# 1b. Download + extract dataset ZIP into /content/ (fast local SSD — avoids
#     Drive's rate limits for many small files). ZIP is committed in repo
#     alongside this script.
import urllib.request, zipfile, io, pathlib
DATASET_ZIP_URL = "https://raw.githubusercontent.com/flowa7021-source/OCR-tool/claude/easyocr-integration-review-3e9pP/colab_release/finetune_ru_colab.zip"
LOCAL_DATASET_DIR = pathlib.Path("/content/finetune_ru")
if not (LOCAL_DATASET_DIR / 'training' / 'labels.csv').exists():
    print(f'Downloading dataset ZIP from {DATASET_ZIP_URL} …')
    req = urllib.request.Request(DATASET_ZIP_URL, headers={'User-Agent': 'colab'})
    with urllib.request.urlopen(req) as r:
        blob = r.read()
    print(f'Downloaded {len(blob) / 1e6:.1f} MB. Extracting …')
    with zipfile.ZipFile(io.BytesIO(blob)) as zf:
        zf.extractall('/content')
    print(f'Dataset extracted to {LOCAL_DATASET_DIR}')
else:
    print(f'Dataset already present at {LOCAL_DATASET_DIR}')
# Sanity check — trainer needs labels.csv + .jpgs in each split.
for split in ('training', 'validation'):
    p = LOCAL_DATASET_DIR / split
    csv = p / 'labels.csv'
    jpgs = list(p.glob('*.jpg'))
    assert csv.exists(), f'Missing {csv}'
    print(f'  {split}: {csv} ({csv.stat().st_size / 1e3:.0f} KB), {len(jpgs)} jpgs')

# 2. Install deps (use Colab's pre-installed torch/torchvision/numpy — only add
#    the trainer's extras. Pinning torch==2.0.1 fails on modern Colab Python.)
import subprocess, sys
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q',
    'natsort', 'lmdb', 'nltk', 'fire', 'pandas',
    'opencv-python-headless', 'Pillow', 'PyYAML'])

# 3. Clone trainer (sparse checkout — only trainer/ subfolder)
import subprocess
subprocess.check_call(['bash', '-c',
    'rm -rf /content/EasyOCR && '
    'git clone --depth 1 --filter=blob:none --sparse '
    'https://github.com/JaidedAI/EasyOCR.git /content/EasyOCR && '
    'cd /content/EasyOCR && '
    'git sparse-checkout set trainer'])

# 4. Fetch stock cyrillic_g2 weights (shipped as a ZIP in EasyOCR releases)
import urllib.request, pathlib, zipfile, io
base_weights = pathlib.Path('/content/base_weights/cyrillic_g2.pth')
base_weights.parent.mkdir(parents=True, exist_ok=True)
if not base_weights.exists():
    urls = [
        'https://github.com/JaidedAI/EasyOCR/releases/download/v1.6.1/cyrillic_g2.zip',
        'https://github.com/JaidedAI/EasyOCR/releases/download/pre-v1.1.6/cyrillic_g2.zip',
    ]
    for url in urls:
        try:
            print(f'Downloading weights from {url} …')
            req = urllib.request.Request(url, headers={'User-Agent': 'easyocr-colab'})
            with urllib.request.urlopen(req) as r:
                blob = r.read()
            with zipfile.ZipFile(io.BytesIO(blob)) as zf:
                # ZIP contains a single .pth at its root.
                members = [n for n in zf.namelist() if n.endswith('.pth')]
                if not members:
                    raise RuntimeError(f'No .pth inside {url}')
                with zf.open(members[0]) as src, open(base_weights, 'wb') as dst:
                    dst.write(src.read())
            break
        except Exception as e:
            print(f'  failed: {e}')
    else:
        raise RuntimeError('Could not download cyrillic_g2.pth — check network.')
print('Base weights:', base_weights, f'({base_weights.stat().st_size / 1e6:.1f} MB)')

# 4b. Patch trainer for PyTorch 2.x / Python 3 compatibility
# - torch._utils._accumulate removed in PyTorch 2.x → itertools.accumulate
# - iterator.next() → next(iterator) (Python 3)
import pathlib
_ds = pathlib.Path('/content/EasyOCR/trainer/dataset.py')
_src = _ds.read_text(encoding='utf-8')
if 'from itertools import accumulate as _accumulate' not in _src:
    _src = _src.replace(
        'from torch._utils import _accumulate',
        'try:\n    from torch._utils import _accumulate\n'
        'except ImportError:\n    from itertools import accumulate as _accumulate'
    )
    _src = _src.replace('data_loader_iter.next()', 'next(data_loader_iter)')
    _src = _src.replace(
        'self.dataloader_iter_list[i].next()',
        'next(self.dataloader_iter_list[i])'
    )
    _ds.write_text(_src, encoding='utf-8')
    print('Patched trainer/dataset.py (PyTorch 2.x / Python 3 compat)')

# 4c. Patch train.py for PyTorch ≥ 2.6 (weights_only=True default rejects
#     arbitrary pickled state_dicts).
_tr = pathlib.Path('/content/EasyOCR/trainer/train.py')
_tsrc = _tr.read_text(encoding='utf-8')
if 'weights_only=False' not in _tsrc:
    _tsrc = _tsrc.replace(
        'pretrained_dict = torch.load(opt.saved_model)',
        'pretrained_dict = torch.load(opt.saved_model, weights_only=False)'
    )
    _tr.write_text(_tsrc, encoding='utf-8')
    print('Patched trainer/train.py (torch.load weights_only=False)')

# 5. Write trainer YAML config
import pathlib
DATA = str(LOCAL_DATASET_DIR)
EPOCHS = 100
BATCH = 32
num_iter = EPOCHS * 1000

import string as _string
_sym = " " + _string.punctuation + " €₽"
_sym_yaml = _sym.replace("'", "''")
cfg = "\n".join([
    "number: '0123456789'",
    f"symbol: '{_sym_yaml}'",
    "lang_char: 'абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'",
    "experiment_name: 'ru_finetune'",
    f"train_data: '{DATA}'",
    f"valid_data: '{DATA}/validation'",
    "manualSeed: 1111",
    "workers: 2",
    f"batch_size: {BATCH}",
    f"num_iter: {num_iter}",
    "valInterval: 500",
    f"saved_model: '{str(base_weights)}'",
    "FT: True",
    "optim: 'adam'",
    "lr: 0.0005",
    "beta1: 0.9",
    "rho: 0.95",
    "eps: 0.00000001",
    "grad_clip: 5",
    "select_data: 'training'",
    "batch_ratio: '1.0'",
    "total_data_usage_ratio: '1.0'",
    "batch_max_length: 34",
    "imgH: 64",
    "imgW: 600",
    "rgb: False",
    "sensitive: True",
    "contrast_adjust: 0.0",
    "data_filtering_off: False",
    "PAD: True",
    "Transformation: 'None'",
    "FeatureExtraction: 'ResNet'",
    "SequenceModeling: 'BiLSTM'",
    "Prediction: 'CTC'",
    "num_fiducial: 20",
    "input_channel: 1",
    "output_channel: 256",
    "hidden_size: 256",
    "decode: 'greedy'",
    "new_prediction: True",
    "freeze_FeatureFxtraction: False",
    "freeze_SequenceModeling: False",
    "device: 'cuda'",
]) + "\n"

cfg_path = pathlib.Path('/content/EasyOCR/trainer/saved_models/ru_finetune.yaml')
cfg_path.parent.mkdir(parents=True, exist_ok=True)
cfg_path.write_text(cfg, encoding='utf-8')
print('Config written:', cfg_path)

# 6. Train (EasyOCR trainer has no argparse __main__ — drive via notebook-style runner)
import subprocess, pathlib
_runner_lines = [
    'import os, sys, yaml',
    'import torch.backends.cudnn as cudnn',
    'sys.path.insert(0, os.getcwd())',
    'from train import train',
    'from utils import AttrDict',
    "with open(sys.argv[1], encoding='utf-8') as f:",
    '    opt = AttrDict(yaml.safe_load(f))',
    'opt.character = opt.number + opt.symbol + opt.lang_char',
    "os.makedirs(f'./saved_models/{opt.experiment_name}', exist_ok=True)",
    'cudnn.benchmark = True',
    'cudnn.deterministic = False',
    'train(opt, amp=False)',
]
_runner = pathlib.Path('/content/EasyOCR/trainer/_runner.py')
_runner.write_text('\n'.join(_runner_lines) + '\n', encoding='utf-8')

# Stream stdout + stderr line-by-line into the Colab cell so a failing
# train() call is actually visible (subprocess.run without capture swallows
# output in notebook kernels). We also force -u (unbuffered) so progress
# prints appear live, not after process exits.
proc = subprocess.Popen(
    ['python', '-u', str(_runner), str(cfg_path)],
    cwd='/content/EasyOCR/trainer',
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    text=True, bufsize=1,
)
for line in proc.stdout:
    print(line, end='')
rc = proc.wait()
print(f'Training finished with exit code {rc}')

# 7. Copy best checkpoint back to Drive (so you can download it after the VM dies)
import shutil, pathlib
best = pathlib.Path('/content/EasyOCR/trainer/saved_models/ru_finetune/best_accuracy.pth')
out_dir = pathlib.Path("/content/drive/MyDrive/finetune_ru") / 'out'
out_dir.mkdir(parents=True, exist_ok=True)
if best.exists():
    dest = out_dir / 'best_accuracy.pth'
    shutil.copy2(best, dest)
    print('Fine-tuned weights saved to Drive:', dest)
    print('Next: copy to resources/easyocr_models/cyrillic_g2.pth, then python build.py')
else:
    print('WARNING: no best_accuracy.pth found — check training log above.')

