
# ── Cell generated by scripts/finetune/kaggle_finetune.py ─────────────────

# 1. Install deps (no torch pinning — use Kaggle's pre-installed GPU torch).
import subprocess, sys
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q',
    'natsort', 'lmdb', 'nltk', 'fire', 'pandas',
    'opencv-python-headless', 'Pillow', 'PyYAML'])

# 2. Download + extract dataset ZIP to /kaggle/working/finetune_ru
#    (GitHub raw — no Drive / no manual upload needed).
import urllib.request, zipfile, io, pathlib, os
DATASET_ZIP_URL = "https://raw.githubusercontent.com/flowa7021-source/OCR-tool/claude/easyocr-integration-review-3e9pP/colab_release/finetune_ru_colab.zip"
LOCAL_DATASET_DIR = pathlib.Path("/kaggle/working/finetune_ru")
os.makedirs(LOCAL_DATASET_DIR.parent, exist_ok=True)
if not (LOCAL_DATASET_DIR / 'training' / 'labels.csv').exists():
    print(f'Downloading dataset ZIP from {DATASET_ZIP_URL} …')
    req = urllib.request.Request(DATASET_ZIP_URL, headers={'User-Agent': 'kaggle'})
    with urllib.request.urlopen(req) as r:
        blob = r.read()
    print(f'Downloaded {len(blob) / 1e6:.1f} MB. Extracting …')
    with zipfile.ZipFile(io.BytesIO(blob)) as zf:
        zf.extractall(str(LOCAL_DATASET_DIR.parent))
    print(f'Dataset extracted to {LOCAL_DATASET_DIR}')
else:
    print(f'Dataset already present at {LOCAL_DATASET_DIR}')
for split in ('training', 'validation'):
    p = LOCAL_DATASET_DIR / split
    csv = p / 'labels.csv'
    jpgs = list(p.glob('*.jpg'))
    assert csv.exists(), f'Missing {csv}'
    print(f'  {split}: {csv} ({csv.stat().st_size / 1e3:.0f} KB), {len(jpgs)} jpgs')

# 3. Clone trainer (sparse checkout — only trainer/ subfolder)
subprocess.check_call(['bash', '-c',
    'rm -rf /kaggle/working/EasyOCR && '
    'git clone --depth 1 --filter=blob:none --sparse '
    'https://github.com/JaidedAI/EasyOCR.git /kaggle/working/EasyOCR && '
    'cd /kaggle/working/EasyOCR && '
    'git sparse-checkout set trainer'])

# 4. Fetch stock cyrillic_g2 weights (v1.6.1 ZIP) — 15 MB
import urllib.request, pathlib, zipfile, io
base_weights = pathlib.Path('/kaggle/working/base_weights/cyrillic_g2.pth')
base_weights.parent.mkdir(parents=True, exist_ok=True)
if not base_weights.exists():
    urls = [
        'https://github.com/JaidedAI/EasyOCR/releases/download/v1.6.1/cyrillic_g2.zip',
        'https://github.com/JaidedAI/EasyOCR/releases/download/pre-v1.1.6/cyrillic_g2.zip',
    ]
    for url in urls:
        try:
            print(f'Downloading weights from {url} …')
            req = urllib.request.Request(url, headers={'User-Agent': 'easyocr-kaggle'})
            with urllib.request.urlopen(req) as r:
                blob = r.read()
            with zipfile.ZipFile(io.BytesIO(blob)) as zf:
                members = [n for n in zf.namelist() if n.endswith('.pth')]
                if not members:
                    raise RuntimeError(f'No .pth inside {url}')
                with zf.open(members[0]) as src, open(base_weights, 'wb') as dst:
                    dst.write(src.read())
            break
        except Exception as e:
            print(f'  failed: {e}')
    else:
        raise RuntimeError('Could not download cyrillic_g2.pth — check network + Kaggle Internet setting.')
print('Base weights:', base_weights, f'({base_weights.stat().st_size / 1e6:.1f} MB)')

# 4b. Patch trainer for PyTorch 2.x / Python 3 compatibility
# - torch._utils._accumulate removed in PyTorch 2.x → itertools.accumulate
# - iterator.next() → next(iterator) (Python 3)
import pathlib
_ds = pathlib.Path('/kaggle/working/EasyOCR/trainer/dataset.py')
_src = _ds.read_text(encoding='utf-8')
if 'from itertools import accumulate as _accumulate' not in _src:
    _src = _src.replace(
        'from torch._utils import _accumulate',
        'try:\n    from torch._utils import _accumulate\n'
        'except ImportError:\n    from itertools import accumulate as _accumulate'
    )
    _src = _src.replace('data_loader_iter.next()', 'next(data_loader_iter)')
    _src = _src.replace(
        'self.dataloader_iter_list[i].next()',
        'next(self.dataloader_iter_list[i])'
    )
    _ds.write_text(_src, encoding='utf-8')
    print('Patched trainer/dataset.py (PyTorch 2.x / Python 3 compat)')

# 4c. Patch train.py for PyTorch ≥ 2.6 (weights_only=True default rejects
#     arbitrary pickled state_dicts).
_tr = pathlib.Path('/kaggle/working/EasyOCR/trainer/train.py')
_tsrc = _tr.read_text(encoding='utf-8')
if 'weights_only=False' not in _tsrc:
    _tsrc = _tsrc.replace(
        'pretrained_dict = torch.load(opt.saved_model)',
        'pretrained_dict = torch.load(opt.saved_model, weights_only=False)'
    )
    _tr.write_text(_tsrc, encoding='utf-8')
    print('Patched trainer/train.py (torch.load weights_only=False)')

# 4d. Patch test.py: validation CTC-loss device mismatch (CPU targets on CUDA preds).
_te = pathlib.Path('/kaggle/working/EasyOCR/trainer/test.py')
_tesrc = _te.read_text(encoding='utf-8')
_old = (
    "            preds_size = torch.IntTensor([preds.size(1)] * batch_size)\n"
    "            # permute 'preds' to use CTCloss format\n"
    "            cost = criterion(preds.log_softmax(2).permute(1, 0, 2), "
    "text_for_loss, preds_size, length_for_loss)"
)
_new = (
    "            preds_size = torch.IntTensor([preds.size(1)] * batch_size).to(device)\n"
    "            # permute 'preds' to use CTCloss format\n"
    "            cost = criterion(preds.log_softmax(2).permute(1, 0, 2), "
    "text_for_loss.to(device), preds_size, length_for_loss.to(device))"
)
if _old in _tesrc:
    _tesrc = _tesrc.replace(_old, _new)
    _te.write_text(_tesrc, encoding='utf-8')
    print('Patched trainer/test.py (CTC-loss device mismatch)')

# 5. Write trainer YAML config
import pathlib
DATA = str(LOCAL_DATASET_DIR)
EPOCHS = 30
BATCH = 32
num_iter = EPOCHS * 1000

import string as _string
_sym = " " + _string.punctuation + " €₽"
_sym_yaml = _sym.replace("'", "''")
cfg = "\n".join([
    "number: '0123456789'",
    f"symbol: '{_sym_yaml}'",
    "lang_char: 'абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'",
    "experiment_name: 'ru_finetune'",
    f"train_data: '{DATA}'",
    f"valid_data: '{DATA}/validation'",
    "manualSeed: 1111",
    "workers: 2",
    f"batch_size: {BATCH}",
    f"num_iter: {num_iter}",
    "valInterval: 100",
    f"saved_model: '{str(base_weights)}'",
    "FT: True",
    "optim: 'adam'",
    "lr: 0.0005",
    "beta1: 0.9",
    "rho: 0.95",
    "eps: 0.00000001",
    "grad_clip: 5",
    "select_data: 'training'",
    "batch_ratio: '1.0'",
    "total_data_usage_ratio: '1.0'",
    "batch_max_length: 34",
    "imgH: 64",
    "imgW: 600",
    "rgb: False",
    "sensitive: True",
    "contrast_adjust: 0.0",
    "data_filtering_off: False",
    "PAD: True",
    "Transformation: 'None'",
    "FeatureExtraction: 'ResNet'",
    "SequenceModeling: 'BiLSTM'",
    "Prediction: 'CTC'",
    "num_fiducial: 20",
    "input_channel: 1",
    "output_channel: 256",
    "hidden_size: 256",
    "decode: 'greedy'",
    "new_prediction: True",
    "freeze_FeatureFxtraction: False",
    "freeze_SequenceModeling: False",
    "device: 'cuda'",
]) + "\n"

cfg_path = pathlib.Path('/kaggle/working/EasyOCR/trainer/saved_models/ru_finetune.yaml')
cfg_path.parent.mkdir(parents=True, exist_ok=True)
cfg_path.write_text(cfg, encoding='utf-8')
print('Config written:', cfg_path)

# 5b. Live-sync best_accuracy.pth to /kaggle/working/out/ every 60 s.
# Trainer writes to saved_models/ru_finetune/best_accuracy.pth whenever
# validation accuracy improves. We copy it to the notebook's output dir
# so that even if the session dies mid-training, the last-best
# checkpoint is downloadable. /kaggle/working/ is persistent for the
# session; files here appear in the notebook's "Output" tab.
import threading, time, shutil
OUTPUT_DIR = pathlib.Path("/kaggle/working/out")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
_sync_stop = threading.Event()

def _sync_checkpoints():
    src = pathlib.Path('/kaggle/working/EasyOCR/trainer/saved_models/ru_finetune/best_accuracy.pth')
    dst = OUTPUT_DIR / 'best_accuracy.pth'
    last_mtime = 0.0
    while not _sync_stop.is_set():
        if src.exists():
            m = src.stat().st_mtime
            if m != last_mtime:
                try:
                    shutil.copy2(src, dst)
                    print(f'[sync] {dst} updated ({dst.stat().st_size / 1e6:.1f} MB)')
                    last_mtime = m
                except OSError as e:
                    print(f'[sync] failed: {e}')
        _sync_stop.wait(60)

_sync_thread = threading.Thread(target=_sync_checkpoints, daemon=True)
_sync_thread.start()
print(f'Checkpoint sync thread running → {OUTPUT_DIR}')

# 6. Train (stream output line-by-line so the log is visible + flushed).
import subprocess, pathlib
_runner_lines = [
    'import os, sys, yaml',
    'import torch.backends.cudnn as cudnn',
    'sys.path.insert(0, os.getcwd())',
    'from train import train',
    'from utils import AttrDict',
    "with open(sys.argv[1], encoding='utf-8') as f:",
    '    opt = AttrDict(yaml.safe_load(f))',
    'opt.character = opt.number + opt.symbol + opt.lang_char',
    "os.makedirs(f'./saved_models/{opt.experiment_name}', exist_ok=True)",
    'cudnn.benchmark = True',
    'cudnn.deterministic = False',
    'train(opt, amp=False)',
]
_runner = pathlib.Path('/kaggle/working/EasyOCR/trainer/_runner.py')
_runner.write_text('\n'.join(_runner_lines) + '\n', encoding='utf-8')

proc = subprocess.Popen(
    ['python', '-u', str(_runner), str(cfg_path)],
    cwd='/kaggle/working/EasyOCR/trainer',
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    text=True, bufsize=1,
)
for line in proc.stdout:
    print(line, end='')
rc = proc.wait()
_sync_stop.set()
print(f'Training finished with exit code {rc}')

# 7. Final checkpoint copy (in case the sync thread missed the last save)
import shutil, pathlib
best = pathlib.Path('/kaggle/working/EasyOCR/trainer/saved_models/ru_finetune/best_accuracy.pth')
if best.exists():
    dest = OUTPUT_DIR / 'best_accuracy.pth'
    shutil.copy2(best, dest)
    print('Fine-tuned weights saved to notebook output:', dest)
    print('Download via the Output panel on the right side of the notebook.')
    print('Next: place at resources/easyocr_models/cyrillic_g2.pth locally, then python build.py')
else:
    print('WARNING: no best_accuracy.pth found — check training log above.')

